### signup user1
POST http://localhost:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "John Doe",
  "email": "JohnDoe@acme.org",
  "password": "password"
}

### signup user2
POST http://localhost:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "Alice Doe",
  "email": "AliceDoe@acme.org",
  "password": "password"
}

### signup user3
POST http://localhost:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "Bob",
  "email": "Bob@acme.org",
  "password": "password"
}

### login user1
POST http://localhost:6688/api/signin
Content-Type: application/json

{
  "email": "JohnDoe@acme.org",
  "password": "password"
}

> {%
    client.global.set("token", response.body.token)
%}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "acme",
  "members": [
    1,
    2
  ],
  "public": false
}

### chat api
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}

### update chat
PATCH http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "acme4",
  "members": [
    1,
    2,
    3
  ],
  "public": true
}

### Delete chat
DELETE http://localhost:6688/api/chats/2
Authorization: Bearer {{token}}

### upload a file
POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; filename="app.yml"
Content-Type: application/octet-stream

< ./chat_server/chat.yml
--Boundary
Content-Disposition: form-data; filename="hello.txt"

Hello world!
--Boundary--

### get file hello.txt
GET http://localhost:6688/api/files/1/c35/419/65321acb48b82be537efafba581c962099.yml
Authorization: Bearer {{token}}

### send a message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "Hello world!",
  "files": []
}

### get messages
GET http://localhost:6688/api/chats/1/messages?limit=6&last_id=5
Authorization: Bearer {{token}}

### get sse
GET http://localhost:6687/events?access_token={{token}}