[package]
edition = "2021"
name = "algo"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
blake3 = "1.5.3"
napi = { version = "2", default-features = false, features = ["full"] }
napi-derive = "2"
oneshot = "0.1.8"
